/**
 * FRONTEND API CONTRACT — single source of truth for the backend handoff.
 *
 * Each entry documents an endpoint the frontend calls, the HTTP method, the
 * required headers, an example request body (where relevant), and the EXACT
 * JSON shape the frontend expects back. The "API Specs" page renders these,
 * grouped by module, as copyable snippets, and the Postman generator builds a
 * collection (with one folder per group) from them.
 */

export type ContractEndpoint = {
  /** Stable id used as React key */
  id: string
  /** Module the endpoint belongs to (used for grouping in the UI + Postman) */
  group: string
  /** Arabic feature title */
  title: string
  method: 'GET' | 'POST' | 'PUT' | 'DELETE'
  /** Path relative to API_BASE_URL */
  path: string
  /** Short Arabic description of when the frontend calls this */
  description: string
  /** Whether the Authorization: Bearer header is required */
  auth: boolean
  /** Example request body the frontend sends (null for GET/DELETE) */
  requestExample: unknown | null
  /** Exact response shape the frontend expects */
  responseExample: unknown
}

const G = {
  authUsers: '1. المصادقة والتحقق والمستخدمون (Auth, KYC & Users)',
  portfolio: '2. الملف الفني والتوفر (Portfolio & Availability)',
  jobs: '3. الوظائف والكاستينج وإدارة الطاقم (Jobs, Casting & Crew)',
  equipment: '4. تأجير المعدات والمواقع (Equipment & Locations)',
  contracts: '5. العقود الذكية والقانونية (Smart Contracts & Legal)',
  chat: '6. الدردشة والتواصل المجتمعي (Chat & Community)',
  vod: '7. الفيديو والبث السينمائي (VOD & Streaming)',
  workshops: '8. ورش العمل والتدريب (Workshops & Training)',
  wallet: '9. المدفوعات والمحفظة والضمان (Payments, Wallet & Escrow)',
  reviews: '10. التقييمات والمراجعات والدعم (Ratings, Reviews & Support)',
  notifications: '11. الإشعارات الفورية (Push Notifications)',
  admin: '12. عمليات الإدارة العليا (Super Admin Operations)',
  dashboard: '13. بيانات لوحة التحكم (Admin Dashboard Data)',
  security: '14. أمان الحساب (Account Security: 2FA & Magic Link)',
  devicePairing: '15. ربط أجهزة المشاهدة (VOD Device Pairing)',
  profileExport: '16. تصدير الملف الشخصي والمعاملات الدقيقة (Profile Export & Micro-transactions)',
  bookingsTrust: '17. الحجوزات والتقييمات والتقسيط (Bookings, Trust & BNPL)',
  assetsMarket: '18. سوق الأصول والتجارة الإلكترونية (Assets Marketplace & E-commerce)',
  productionSuite: '19. غرفة عمليات الإنتاج (Production Manager Suite)',
  crud: '20. الإدارة والتحرير (CRUD & Entity Management)',
  leaderboard: '21. المتصدرون والتصنيفات (Leaderboards & Rankings)',
  vodPlus: '22. متجر VOD وحفلات المشاهدة (VOD Store & Watch Parties)',
} as const

export const API_CONTRACT: ContractEndpoint[] = [
  // ── 1. AUTH, KYC & USERS ────────────────────────────────────────────────
  {
    id: 'auth-register',
    group: G.authUsers,
    title: 'إنشاء حساب (Register)',
    method: 'POST',
    path: '/auth/register',
    description: 'تسجيل مستخدم جديد (فنان، شركة، أو طاقم). يُعيد توكن وبيانات الحساب.',
    auth: false,
    requestExample: {
      name: 'سارة محمد',
      email: 'sara@example.com',
      password: '••••••••',
      role: 'freelancer',
      country: 'KW',
    },
    responseExample: {
      token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
      user: { id: 101, name: 'سارة محمد', role: 'freelancer', kycStatus: 'pending' },
    },
  },
  {
    id: 'auth-login',
    group: G.authUsers,
    title: 'تسجيل الدخول (Login / JWT)',
    method: 'POST',
    path: '/auth/login',
    description: 'تسجيل الدخول. يجب أن يُعيد توكن JWT وبيانات المستخدم.',
    auth: false,
    requestExample: { email: 'admin@askcrew.com', password: '••••••••' },
    responseExample: {
      token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
      user: { id: 1, name: 'عامر الفضلي', role: 'super_admin' },
    },
  },
  {
    id: 'kyc-upload',
    group: G.authUsers,
    title: 'رفع وثيقة الهوية (KYC Upload)',
    method: 'POST',
    path: '/kyc/upload',
    description: 'رفع صورة الهوية الحكومية للتحقق. يُرسَل عادةً كـ multipart أو رابط مرفوع.',
    auth: true,
    requestExample: {
      docType: 'national_id',
      documentUrl: 'https://uploads.askcrew.com/kyc/abc123.jpg',
      country: 'KW',
    },
    responseExample: { id: 'kyc_551', status: 'under_review', submittedAt: '2026-06-22T09:00:00Z' },
  },
  {
    id: 'kyc-verify-union',
    group: G.authUsers,
    title: 'التحقق من نقابة (Verify Union)',
    method: 'POST',
    path: '/kyc/verify-union',
    description: 'التحقق من عضوية نقابة مثل SAG-AFTRA أو نقابة سينمائية محلية.',
    auth: true,
    requestExample: { union: 'SAG-AFTRA', membershipId: 'SA-882913', fullName: 'Sarah Lambert' },
    responseExample: { verified: true, union: 'SAG-AFTRA', validUntil: '2027-01-01' },
  },
  {
    id: 'users-profile',
    group: G.authUsers,
    title: 'جلب الملف الشخصي (Get Profile)',
    method: 'GET',
    path: '/users/profile',
    description: 'تفاصيل المستخدم الحالي لعرض البروفايل ولوحة الحساب.',
    auth: true,
    requestExample: null,
    responseExample: {
      id: 101,
      name: 'سارة محمد',
      role: 'freelancer',
      kycStatus: 'verified',
      rating: 4.8,
      timezone: 'Asia/Kuwait',
    },
  },
  {
    id: 'users-detail',
    group: G.authUsers,
    title: 'تفاصيل المستخدم الكاملة + بيانات ديناميكية (User Details + Dynamic Metadata)',
    method: 'GET',
    path: '/users/:id/details',
    description:
      'يُغذّي لوحة "تفاصيل المستخدم" الجانبية في الـ CRM. يدعم أنواع حسابات متعددة عبر الحقل roleType (company | student | viewer | freelancer | crew | vip | admin)، ومصفوفات ديناميكية للمواصفات (specifications) والصلاحيات (permissions)، ونقاط المكافآت والباقة. الحقل الأهم هو metadata: كائن (Record<string, any>) حر — أي عمود إضافي في قاعدة البيانات يُمرَّر داخله سيُعرَض تلقائياً في الواجهة كصفّ منسّق دون أي تعديل في الفرونت-إند. أمثلة أدناه توضّح اختلاف metadata حسب نوع الحساب.',
    auth: true,
    requestExample: null,
    responseExample: {
      id: 5,
      name: 'دانة الرشيد',
      roleType: 'company',
      tier: 'VIP',
      status: 'active',
      specifications: ['إنتاج درامي', 'إعلانات تجارية'],
      permissions: ['حساب شركة', 'إدارة الفريق', 'فوترة'],
      financial: {
        iban: 'KW02 NBOK 0000 0000 0000 9988 1122 05',
        verified: true,
        availableKwd: 28400,
        pendingEscrowKwd: 12600,
        points: 41200,
        plan: 'VIP',
        planExpiry: '2027-06-05',
      },
      // متغيّر حسب نوع الحساب — الواجهة تعرض أي مفتاح هنا تلقائياً:
      metadata: {
        commercialRegister: '123456/2021',
        taxId: 'KW-TAX-998877',
        companyProfile: 'أكثر من 15 عاماً في الإنتاج الإعلامي',
        employees: 64,
      },
      _metadataExamplesByRole: {
        company: { commercialRegister: '123456/2021', taxId: 'KW-TAX-998877', companyProfile: '...' },
        student: { university: 'جامعة الكويت', major: 'إنتاج تلفزيوني', graduationYear: 2027, studentId: 'KU-2023-114502' },
        viewer: { watchTime: '142 ساعة', subscriptionHistory: 'شهري (مُلغى)', favoriteGenres: 'دراما، أكشن' },
        freelancer: { equipment: 'كاميرا Sony FX6، عدسات Zeiss', unionId: 'DIR-LB-2019-0451', availability: 'بدوام جزئي' },
      },
    },
  },
  {
    id: 'users-update-metadata',
    group: G.authUsers,
    title: 'تحديث البيانات الديناميكية (Update Dynamic Metadata)',
    method: 'PUT',
    path: '/users/:id/metadata',
    description:
      'تحديث/إضافة حقول ديناميكية لنوع الحساب دون تغيير المخطط. مرّر أي أزواج مفتاح/قيمة داخل metadata وستُحفظ وتُعرَض في لوحة التفاصيل تلقائياً.',
    auth: true,
    requestExample: {
      roleType: 'student',
      metadata: {
        university: 'جامعة الكويت — كلية الإعلام',
        major: 'إنتاج تلفزيوني وسينمائي',
        graduationYear: 2027,
        studentId: 'KU-2023-114502',
      },
    },
    responseExample: { success: true, id: 2, updatedKeys: ['university', 'major', 'graduationYear', 'studentId'] },
  },

  // ── 2. PORTFOLIO & AVAILABILITY ─────────────────────────────────────────
  {
    id: 'portfolio-resume',
    group: G.portfolio,
    title: 'تحديث السيرة والـ PDF (Update Resume)',
    method: 'PUT',
    path: '/portfolio/resume',
    description: 'تحديث النب��ة التعريفية ورفع ملف السيرة الذاتية (PDF).',
    auth: true,
    requestExample: {
      bio: 'مديرة تصوير حائزة على جوائز...',
      resumeUrl: 'https://uploads.askcrew.com/cv/sara.pdf',
      skills: ['تصوير', 'إضاءة', 'مونتاج'],
    },
    responseExample: { success: true, updatedAt: '2026-06-22T10:00:00Z' },
  },
  {
    id: 'portfolio-showreel',
    group: G.portfolio,
    title: 'رفع شو-ريل (Upload Showreel)',
    method: 'POST',
    path: '/portfolio/showreel',
    description: 'إضافة رابط/ملف فيديو لأعمال الفنان (Showreel).',
    auth: true,
    requestExample: { title: 'أعمالي 2026', videoUrl: 'https://vimeo.com/123456', durationSec: 142 },
    responseExample: { id: 'reel_77', status: 'processing' },
  },
  {
    id: 'calendar-availability',
    group: G.portfolio,
    title: 'تحديث التوفّر (Availability)',
    method: 'PUT',
    path: '/calendar/availability',
    description: 'تحديث أيام التوفّر والأيام المحجوزة (block-out) للفنان.',
    auth: true,
    requestExample: {
      available: ['2026-07-01', '2026-07-02'],
      blocked: ['2026-07-10', '2026-07-11'],
    },
    responseExample: { success: true, blockedCount: 2, availableCount: 2 },
  },

  // ── 3. JOBS, CASTING & CREW ─────────────────────────────────────────────
  {
    id: 'jobs-create',
    group: G.jobs,
    title: '��نشاء وظيفة/كاستينج (Create Job)',
    method: 'POST',
    path: '/jobs',
    description: 'نشر إعلان كا��تينج أو وظيفة طاقم.',
    auth: true,
    requestExample: {
      title: 'مطلوب مدير تصوير',
      type: 'crew',
      location: 'الكويت',
      budget: { amount: 1200, currency: 'KWD' },
      shootDates: ['2026-08-01', '2026-08-05'],
    },
    responseExample: { id: 'job_312', status: 'open', applicants: 0 },
  },
  {
    id: 'jobs-apply',
    group: G.jobs,
    title: 'تقديم طلب (Apply)',
    method: 'POST',
    path: '/jobs/apply',
    description: 'تقديم فنان طلباً على وظيفة/كاستينج.',
    auth: true,
    requestExample: { jobId: 'job_312', coverNote: 'لدي خبرة 8 سنوات...', expectedRate: 1000 },
    responseExample: { applicationId: 'app_9001', status: 'submitted' },
  },
  {
    id: 'jobs-application-status',
    group: G.jobs,
    title: 'قبول/رفض متقدّم (Update Application)',
    method: 'PUT',
    path: '/jobs/applications/:id/status',
    description: 'تغيير حالة طلب التقديم من قِبَل المخرج (قبول/رفض).',
    auth: true,
    requestExample: { status: 'accepted', message: 'مرحباً بك في الفريق' },
    responseExample: { applicationId: 'app_9001', status: 'accepted' },
  },
  {
    id: 'projects-call-sheet',
    group: G.jobs,
    title: 'توليد كول-شيت (Call Sheet)',
    method: 'POST',
    path: '/projects/call-sheet',
    description: 'توليد وتوزيع جدول التصوير اليومي (Call Sheet) على الطاقم.',
    auth: true,
    requestExample: {
      projectId: 'proj_55',
      date: '2026-08-01',
      callTime: '06:30',
      location: 'استوديو الكويت 2',
      crewIds: [101, 102, 103],
    },
    responseExample: { id: 'cs_2201', pdfUrl: 'https://docs.askcrew.com/cs_2201.pdf', notified: 3 },
  },

  // ── 4. EQUIPMENT & LOCATIONS ────────────────────────────────────────────
  {
    id: 'equipment-create',
    group: G.equipment,
    title: 'إدراج معدّة (List Gear)',
    method: 'POST',
    path: '/equipment',
    description: 'إدراج كاميرا/معدّة جديدة للتأجير.',
    auth: true,
    requestExample: {
      name: 'ARRI Alexa Mini',
      category: 'camera',
      pricePerDay: { amount: 250, currency: 'KWD' },
      location: { lat: 29.37, lng: 47.98 },
    },
    responseExample: { id: 'eq_440', status: 'available' },
  },
  {
    id: 'equipment-nearby',
    group: G.equipment,
    title: 'بحث جغرافي عن معدات (Nearby)',
    method: 'GET',
    path: '/equipment/nearby?lat=29.37&lng=47.98&radiusKm=25',
    description: 'بحث ضمن نطاق جغرافي (PostGIS radius) عن معدات قريبة.',
    auth: true,
    requestExample: null,
    responseExample: {
      data: [{ id: 'eq_440', name: 'ARRI Alexa Mini', distanceKm: 3.2, pricePerDay: 250 }],
      total: 1,
    },
  },
  {
    id: 'equipment-book',
    group: G.equipment,
    title: 'حجز معدّة (Book Equipment)',
    method: 'POST',
    path: '/equipment/book',
    description: 'حجز معدّة لتواريخ محددة ودفع العربون.',
    auth: true,
    requestExample: { equipmentId: 'eq_440', from: '2026-08-01', to: '2026-08-03', deposit: 250 },
    responseExample: { bookingId: 'bk_771', status: 'reserved', total: 750, currency: 'KWD' },
  },
  {
    id: 'locations-book',
    group: G.equipment,
    title: 'حجز موقع تصوير (Book Location)',
    method: 'POST',
    path: '/locations/book',
    description: 'حجز موقع تصوير سينمائي لتواريخ محددة.',
    auth: true,
    requestExample: { locationId: 'loc_88', from: '2026-08-02', to: '2026-08-02', crewSize: 12 },
    responseExample: { bookingId: 'lbk_330', status: 'reserved', permitRequired: true },
  },

  // ── 5. SMART CONTRACTS & LEGAL ──────────────────────────────────────────
  {
    id: 'contracts-generate',
    group: G.contracts,
    title: 'توليد عقد ثنائي اللغة (Generate)',
    method: 'POST',
    path: '/contracts/generate',
    description: 'توليد عقد PDF ثنائي اللغة (عربي/إنجليزي) من بنود المشروع.',
    auth: true,
    requestExample: {
      projectId: 'proj_55',
      parties: { client: 12, freelancer: 101 },
      amount: { value: 1200, currency: 'KWD' },
      terms: 'تسليم خلال 30 يوماً...',
      bilingual: true,
    },
    responseExample: { contractId: 'ct_990', pdfUrl: 'https://docs.askcrew.com/ct_990.pdf', status: 'draft' },
  },
  {
    id: 'contracts-sign',
    group: G.contracts,
    title: 'توقيع رقمي (Sign Contract)',
    method: 'POST',
    path: '/contracts/sign',
    description: 'اعتماد التوقيع الرقم�� مع ختم زمني وبصمة IP.',
    auth: true,
    requestExample: {
      contractId: 'ct_990',
      signatureImage: 'data:image/png;base64,iVBORw0KGgo...',
      signerId: 101,
    },
    responseExample: {
      contractId: 'ct_990',
      status: 'signed',
      signedAt: '2026-06-22T11:15:00Z',
      ip: '37.x.x.x',
    },
  },
  {
    id: 'contracts-custom',
    group: G.contracts,
    title: 'عقد مخصّص ببنود JSON (Custom Contract)',
    method: 'POST',
    path: '/contracts/custom',
    description:
      'إنشاء عقد مخصّص من بنود ديناميكية (Custom Clauses) مع جدول دفعات مرتبط بالضمان (Escrow Milestones). يقبل حمولة JSON كاملة لبناء عقد غير قياسي.',
    auth: true,
    requestExample: {
      projectId: 'proj_55',
      parties: { client: 12, freelancer: 101 },
      currency: 'KWD',
      clauses: [
        { id: 'c1', title: 'نطاق العمل', body: 'تصوير 3 أيام بدقة 4K...', mandatory: true },
        { id: 'c2', title: 'حقوق الملكية', body: 'تنتقل الحقوق بعد السداد الكامل.', mandatory: true },
        { id: 'c3', title: 'بند السرية (NDA)', body: 'سرية تامة لمدة 24 شهراً.', mandatory: false },
      ],
      milestones: [
        { label: 'دفعة مقدّمة', percent: 40, escrow: true },
        { label: 'التسليم النهائي', percent: 60, escrow: true },
      ],
      bilingual: true,
    },
    responseExample: {
      contractId: 'ct_1024',
      status: 'draft',
      clauseCount: 3,
      pdfUrl: 'https://docs.askcrew.com/ct_1024.pdf',
      escrowMilestones: 2,
    },
  },

  // ── 6. CHAT & COMMUNITY ─────────────────────────────────────────────────
  {
    id: 'chat-messages',
    group: G.chat,
    title: 'جلب الرسائل (Fetch Messages)',
    method: 'GET',
    path: '/chat/messages?conversationId=conv_12&limit=30',
    description: 'جلب سجل محادثة فردية أو جماعية للمشروع.',
    auth: true,
    requestExample: null,
    responseExample: {
      data: [
        {
          id: 'msg_1',
          senderId: 102,
          text: 'هل يمكننا تغيير الموقع؟',
          lang: 'ar',
          sentAt: '2026-06-22T10:02:00Z',
          read: true,
        },
      ],
      hasMore: false,
    },
  },
  {
    id: 'chat-send',
    group: G.chat,
    title: 'إرسال رسالة/مرفق (Send Message)',
    method: 'POST',
    path: '/chat/send',
    description: 'إرسال نص أو مرفق (سكربت/صورة) داخل المحادثة.',
    auth: true,
    requestExample: {
      conversationId: 'conv_12',
      text: 'تم، سأرسل النسخة المعدّلة',
      attachments: [{ url: 'https://uploads.askcrew.com/script.pdf', type: 'pdf' }],
    },
    responseExample: { id: 'msg_2', status: 'sent', sentAt: '2026-06-22T10:05:00Z' },
  },
  {
    id: 'feed-posts',
    group: G.chat,
    title: 'نشر منشور مجتمعي (Create Post)',
    method: 'POST',
    path: '/feed/posts',
    description: 'نشر تحديث نصي/وسائط على خلاصة المجتمع.',
    auth: true,
    requestExample: { text: 'انتهينا من تصوير الفيلم!', mediaUrls: ['https://uploads.askcrew.com/p1.jpg'] },
    responseExample: { id: 'post_410', likes: 0, comments: 0, createdAt: '2026-06-22T12:00:00Z' },
  },
  {
    id: 'connections-follow',
    group: G.chat,
    title: 'متابعة محترف (Follow)',
    method: 'POST',
    path: '/connections/follow',
    description: 'متابعة ملف محترف آخر للتشبيك المهني.',
    auth: true,
    requestExample: { targetUserId: 205 },
    responseExample: { following: true, followersCount: 1342 },
  },

  // ── 7. VOD & STREAMING ──────────────────────────────────────────────────
  {
    id: 'vod-upload',
    group: G.vod,
    title: 'رابط رفع الفيديو (Presigned URL)',
    method: 'POST',
    path: '/vod/upload',
    description: 'توليد رابط AWS S3 مُوقّع مسبقاً (Presigned URL) لرفع الفيديو مباشرة.',
    auth: true,
    requestExample: { filename: 'movie_final.mp4', contentType: 'video/mp4', sizeBytes: 524288000 },
    responseExample: {
      uploadUrl: 'https://s3.amazonaws.com/askcrew-vod/...&X-Amz-Signature=...',
      assetId: 'vod_120',
      expiresIn: 900,
    },
  },
  {
    id: 'vod-drm',
    group: G.vod,
    title: 'ضبط DRM والحجب الجغرافي (Set DRM)',
    method: 'PUT',
    path: '/vod/drm',
    description: 'ضبط قواعد الحماية (DRM) والحجب الجغرافي للفيديو.',
    auth: true,
    requestExample: {
      assetId: 'vod_120',
      drm: 'widevine',
      geoBlock: { mode: 'allow', countries: ['KW', 'SA', 'AE'] },
    },
    responseExample: { assetId: 'vod_120', drmEnabled: true, geoRulesApplied: 3 },
  },
  {
    id: 'vod-drm-screenshot',
    group: G.vod,
    title: 'حماية لقطة الشاشة (Screenshot DRM)',
    method: 'PUT',
    path: '/vod/drm/screenshot-protection',
    description:
      'تفعيل منع التقاط الشاشة والتسجيل (Screen Capture/Recording). عند التفعيل يتحوّل الفيديو إلى شاشة سوداء في لقطة الشاشة على iOS/Android/Web.',
    auth: true,
    requestExample: {
      assetId: 'vod_120',
      enabled: true,
      blackoutOnCapture: true,
      platforms: ['ios', 'android', 'web'],
    },
    responseExample: { assetId: 'vod_120', screenshotProtection: true, updatedAt: '2026-06-23T18:00:00Z' },
  },
  {
    id: 'vod-drm-fingerprint',
    group: G.vod,
    title: 'البصمة المائية الخفية (Invisible Fingerprint)',
    method: 'PUT',
    path: '/vod/drm/fingerprint',
    description:
      'حقن بصمة مائية خفية (Forensic Watermark) فريدة لكل مشاهد داخل تدفّق الفيديو لتتبّع مصدر أي تسريب. تربط معرّف المستخدم بالجلسة.',
    auth: true,
    requestExample: {
      assetId: 'vod_120',
      enabled: true,
      type: 'forensic',
      payload: { userId: 101, sessionId: 'sess_9af2', opacity: 0.02 },
    },
    responseExample: {
      assetId: 'vod_120',
      fingerprintEnabled: true,
      watermarkId: 'wm_77c1',
      traceable: true,
    },
  },
  {
    id: 'vod-drm-vpn-block',
    group: G.vod,
    title: 'حجب VPN والبروكسي (VPN / Proxy Blocking)',
    method: 'PUT',
    path: '/vod/drm/vpn-block',
    description:
      'رفض جلسات البث القادمة من VPN أو Proxy أو Tor لمنع تجاوز الحجب الجغرافي. يُرجِع 403 عند اكتشاف عنوان IP مُقنّع.',
    auth: true,
    requestExample: {
      assetId: 'vod_120',
      blockVpn: true,
      blockProxy: true,
      blockTor: true,
      action: 'deny_stream',
    },
    responseExample: {
      assetId: 'vod_120',
      vpnBlockEnabled: true,
      detectionProvider: 'ipqualityscore',
      blockedSessionsToday: 14,
    },
  },
  {
    id: 'vod-purchase',
    group: G.vod,
    title: 'شراء تذكرة مشاهدة (Purchase)',
    method: 'POST',
    path: '/vod/purchase',
    description: 'شراء وصول/تذكرة لمشاهدة فيلم.',
    auth: true,
    requestExample: { assetId: 'vod_120', method: 'knet' },
    responseExample: { orderId: 'ord_551', access: 'granted', expiresAt: '2026-06-25T00:00:00Z' },
  },
  {
    id: 'vod-stream',
    group: G.vod,
    title: 'رابط البث (HLS Stream)',
    method: 'GET',
    path: '/vod/stream?assetId=vod_120',
    description: 'جلب رابط بث HLS بعد التحقق من الوصول وقواعد الحجب.',
    auth: true,
    requestExample: null,
    responseExample: { hlsUrl: 'https://stream.askcrew.com/vod_120/master.m3u8', token: 'tok_...' },
  },

  // ── 8. WORKSHOPS & TRAINING ─────────────────────────────────────────────
  {
    id: 'workshops-create',
    group: G.workshops,
    title: 'إنشاء ورشة (Create Workshop)',
    method: 'POST',
    path: '/workshops',
    description: 'إنشاء جلسة تدريبية/ورشة جديدة.',
    auth: true,
    requestExample: {
      title: 'أساسيات الإخراج السينمائي',
      seats: 30,
      price: { amount: 45, currency: 'KWD' },
      startsAt: '2026-09-01T16:00:00Z',
    },
    responseExample: { id: 'ws_77', status: 'open', seatsLeft: 30 },
  },
  {
    id: 'workshops-enroll',
    group: G.workshops,
    title: 'تسجيل طالب (Enroll)',
    method: 'POST',
    path: '/workshops/enroll',
    description: 'تسجيل طالب ومعالجة رسوم الورشة.',
    auth: true,
    requestExample: { workshopId: 'ws_77', method: 'knet' },
    responseExample: { enrollmentId: 'en_900', status: 'confirmed', seatsLeft: 29 },
  },

  // ── 9. PAYMENTS, WALLET & ESCROW ────────────────────────────────────────
  {
    id: 'payments-checkout',
    group: G.wallet,
    title: 'بدء الدفع (Checkout)',
    method: 'POST',
    path: '/payments/checkout',
    description: 'تهيئة جلسة دفع عبر بوابة (Stripe / Tap / K-NET).',
    auth: true,
    requestExample: { packageId: 'vip', cycle: 'annual', country: 'KW' },
    responseExample: {
      sessionId: 'cs_test_a1b2',
      checkoutUrl: 'https://pay.askcrew.com/cs_test_a1b2',
      gateway: 'knet',
      amount: 144,
      currency: 'KWD',
    },
  },
  {
    id: 'wallet-balance',
    group: G.wallet,
    title: 'رصيد المحفظة (Balance)',
    method: 'GET',
    path: '/wallet/balance',
    description: 'عرض الرصيد المتاح مقابل المحجوز في الضمان (Escrow).',
    auth: true,
    requestExample: null,
    responseExample: {
      available: 1850.5,
      escrowHold: 600.0,
      lifetime: 12400.0,
      currency: 'KWD',
    },
  },
  {
    id: 'wallet-withdraw',
    group: G.wallet,
    title: 'طلب سحب (Withdraw)',
    method: 'POST',
    path: '/wallet/withdraw',
    description: 'طلب تحويل بنكي للأموال المتاحة.',
    auth: true,
    requestExample: { amount: 1000, currency: 'KWD', iban: 'KW81CBKU0000000000001234560101' },
    responseExample: { withdrawalId: 'wd_220', status: 'processing', etaDays: 3 },
  },
  {
    id: 'wallet-bank-details',
    group: G.wallet,
    title: 'حفظ البيانات البنكية (Save Bank Details)',
    method: 'POST',
    path: '/wallet/bank-details',
    description: 'حفظ والتحقق من بيانات الآيبان (IBAN) المطلوبة قبل تفعيل السحب من المحفظة.',
    auth: true,
    requestExample: {
      iban: 'KW81CBKU0000000000001234560101',
      bankName: 'بنك الكويت الوطني',
      accountHolder: 'سارة محمد',
    },
    responseExample: {
      iban: 'KW81CBKU0000000000001234560101',
      bankName: 'بنك الكويت الوطني',
      accountHolder: 'سارة محمد',
      verified: true,
    },
  },
  {
    id: 'escrow-release',
    group: G.wallet,
    title: 'الإفراج عن دفعة ضمان (Release Escrow)',
    method: 'POST',
    path: '/escrow/release',
    description:
      'تأكيد اكتمال المشروع والإفراج عن المبلغ المحجوز للمستقل، مع خصم عمولة المنصة تلقائياً ونقل الصافي إلى الرصيد المتاح.',
    auth: true,
    requestExample: { txnId: 'ESC-4012' },
    responseExample: {
      pendingEscrow: 5480,
      available: 4920.5,
      totalWithdrawn: 18650,
      commissionRate: 0.1,
      currency: 'KWD',
    },
  },
  {
    id: 'admin-wallet-verify',
    group: G.wallet,
    title: 'تفعيل التحقق المالي (Financial Verification)',
    method: 'PUT',
    path: '/admin/wallet/financial-verification',
    description:
      'تبديل حالة التحقق المالي للمستخدم من قِبَل الإدارة. عند الإيقاف تُقفل المحفظة ويُمنع السحب نهائياً.',
    auth: true,
    requestExample: { userId: 101, verified: true },
    responseExample: { userId: 101, financiallyVerified: true, walletLocked: false },
  },
  {
    id: 'disputes-list',
    group: G.wallet,
    title: 'قائمة النزاعات (List Disputes)',
    method: 'GET',
    path: '/disputes',
    description: 'جلب جميع نزاعات الضمان المفتوحة والمغلقة لعرضها في مركز فضّ النزاعات والتحكيم.',
    auth: true,
    requestExample: null,
    responseExample: {
      data: [
        {
          id: 'DSP-001',
          txnId: 'ESC-4012',
          project: 'إعلان تجاري — الخليج',
          client: 'خالد الفهد',
          freelancer: 'سارة محمد',
          amountKwd: 1200,
          reason: 'خلاف على نطاق التسليم',
          status: 'open',
          openedAt: '2026-06-21T10:00:00Z',
        },
      ],
      total: 1,
    },
  },
  {
    id: 'disputes-open',
    group: G.wallet,
    title: 'فتح نزاع على الضمان (Open Dispute)',
    method: 'POST',
    path: '/disputes',
    description: 'فتح نزاع جديد على معاملة ضمان مما يُجمّد المبلغ المحجوز حتى صدور قرار التحكيم.',
    auth: true,
    requestExample: { txnId: 'ESC-4012', reason: 'لم يتم تسليم الملفات الأصلية بالدقة المتفق عليها.' },
    responseExample: {
      id: 'DSP-002',
      txnId: 'ESC-4012',
      status: 'open',
      amountKwd: 1200,
      openedAt: '2026-06-23T12:00:00Z',
    },
  },
  {
    id: 'disputes-evidence',
    group: G.wallet,
    title: 'إضافة دليل/رسالة (Add Evidence)',
    method: 'POST',
    path: '/disputes/:id/evidence',
    description: 'إضافة رسالة أو مرفق إثبات إلى سجل النزاع من العميل أو المستقل أو الإدارة.',
    auth: true,
    requestExample: {
      author: 'admin',
      name: 'الإدارة',
      text: 'يرجى رفع نسخة العقد الموقّعة لمراجعتها.',
      attachment: 'https://uploads.askcrew.com/disputes/contract_ct990.pdf',
    },
    responseExample: {
      id: 'evd_55',
      author: 'admin',
      name: 'الإدارة',
      text: 'يرجى رفع نسخة العقد الموقّعة لمراجعتها.',
      time: '2026-06-23T12:05:00Z',
    },
  },
  {
    id: 'disputes-resolve',
    group: G.wallet,
    title: 'قرار التحكيم (Resolve Dispute)',
    method: 'PUT',
    path: '/disputes/:id/resolve',
    description:
      'إصدار قرار التحكيم النهائي. "refund" يعيد المبلغ للعميل، و"release" يُفرج عنه للمستقل بعد خصم العمولة. القرار مُلزِم ويُغلق النزاع.',
    auth: true,
    requestExample: { outcome: 'release' },
    responseExample: {
      dispute: { id: 'DSP-001', status: 'released', resolvedAt: '2026-06-23T13:00:00Z' },
      wallet: { pendingEscrow: 4280, available: 6000.5, currency: 'KWD' },
    },
  },

  // ── 10. RATINGS, REVIEWS & SUPPORT ──────────────────────────────────────
  {
    id: 'reviews-create',
    group: G.reviews,
    title: 'إضافة تقييم (Submit Review)',
    method: 'POST',
    path: '/reviews',
    description: 'تقييم من 1-5 نجوم بعد اكتمال العقد.',
    auth: true,
    requestExample: { contractId: 'ct_990', revieweeId: 101, rating: 5, comment: 'احترافية عالية' },
    responseExample: { id: 'rev_700', rating: 5, createdAt: '2026-06-22T13:00:00Z' },
  },
  {
    id: 'reviews-user',
    group: G.reviews,
    title: 'تقييمات مستخدم (User Reviews)',
    method: 'GET',
    path: '/reviews/user/:id',
    description: 'جلب متوسط التقييم والتعليقات لمستخدم.',
    auth: false,
    requestExample: null,
    responseExample: {
      userId: 101,
      average: 4.8,
      count: 36,
      breakdown: { 5: 28, 4: 6, 3: 2, 2: 0, 1: 0 },
    },
  },
  {
    id: 'tickets-create',
    group: G.reviews,
    title: 'فتح تذكرة دعم (Open Ticket)',
    method: 'POST',
    path: '/tickets',
    description: 'فتح نزاع أو تذكرة دعم فني.',
    auth: true,
    requestExample: { subject: 'مشكلة في الدفع', category: 'billing', message: 'لم تتم العملية...' },
    responseExample: { id: 'tk_4410', status: 'open', priority: 'normal' },
  },

  // ── 11. PUSH NOTIFICATIONS ──────────────────────────────────────────────
  {
    id: 'notifications-register-device',
    group: G.notifications,
    title: '��سجيل جهاز (Register Device)',
    method: 'POST',
    path: '/notifications/register-device',
    description: 'حفظ توكن جهاز (FCM/APNs) لإرسال الإشعارات.',
    auth: true,
    requestExample: { platform: 'ios', token: 'fcm_token_abc123', deviceId: 'dev_55' },
    responseExample: { success: true, registeredAt: '2026-06-22T13:30:00Z' },
  },
  {
    id: 'notifications-send',
    group: G.notifications,
    title: 'إرسال إشعار (Send Push)',
    method: 'POST',
    path: '/notifications/send',
    description: 'إطلاق إشعار فوري لتطبيق الجوال (إداري).',
    auth: true,
    requestExample: {
      target: { userIds: [101, 102] },
      title: 'تم قبول طلبك',
      body: 'تهانينا! تم قبولك في المشروع.',
    },
    responseExample: { sent: 2, failed: 0, messageId: 'msg_push_88' },
  },

  // ── 12. SUPER ADMIN OPERATIONS ──────────────────────────────────────────
  {
    id: 'admin-analytics',
    group: G.admin,
    title: 'تحليلات المنصة (Platform Analytics)',
    method: 'GET',
    path: '/admin/analytics',
    description: 'مؤشرات المنصة: الإيراد الشهري المتكرر، معدل التسرّب، المستخدمون النشطون.',
    auth: true,
    requestExample: null,
    responseExample: {
      mrr: 48200,
      churnRate: 2.1,
      activeUsers: 8402,
      gmv: 312000,
      currency: 'KWD',
    },
  },
  {
    id: 'admin-kyc-review',
    group: G.admin,
    title: 'مراجعة KYC (Approve/Reject)',
    method: 'PUT',
    path: '/admin/kyc/review',
    description: 'قبول أو رفض وثائق التحقق المقدّمة.',
    auth: true,
    requestExample: { kycId: 'kyc_551', decision: 'approved', note: 'وثيقة واضحة' },
    responseExample: { kycId: 'kyc_551', status: 'verified', reviewedBy: 1 },
  },
  {
    id: 'admin-users-ban',
    group: G.admin,
    title: 'حظر/تعليق مستخدم (Ban User)',
    method: 'PUT',
    path: '/admin/users/ban',
    description: 'تعليق أو حظر حساب مستخدم.',
    auth: true,
    requestExample: { userId: 309, action: 'suspend', reason: 'مخالفة الشروط', days: 30 },
    responseExample: { userId: 309, status: 'suspended', until: '2026-07-22T00:00:00Z' },
  },
  {
    id: 'admin-platform-fees',
    group: G.admin,
    title: 'ضبط العمولة (Platform Fees)',
    method: 'PUT',
    path: '/admin/platform/fees',
    description: 'تعديل نسبة عمولة المنصة ديناميكياً.',
    auth: true,
    requestExample: { commissionPercent: 12.5, appliesTo: 'all' },
    responseExample: { commissionPercent: 12.5, effectiveAt: '2026-07-01T00:00:00Z' },
  },

  // ── 13. ADMIN DASHBOARD DATA (existing UI-backing endpoints) ────────────
  {
    id: 'users-list',
    group: G.dashboard,
    title: 'قائمة المستخدمين (Users List)',
    method: 'GET',
    path: '/users',
    description: 'تُستخدم في صفحة إدارة المستخدمين (CRM) لعرض كل الحسابات.',
    auth: true,
    requestExample: null,
    responseExample: {
      data: [
        {
          id: 101,
          name: 'سارة محمد',
          email: 'sara@example.com',
          status: 'active',
          twoFA: true,
          lastSeen: '2026-06-19T08:30:00Z',
          events: 248,
        },
      ],
      total: 1,
      page: 1,
      perPage: 20,
    },
  },
  {
    id: 'companies-list',
    group: G.dashboard,
    title: 'قائمة الشركات (Companies List)',
    method: 'GET',
    path: '/companies',
    description: 'تُستخدم في لوحة الشركات (B2B) لعرض العقود والمقاعد.',
    auth: true,
    requestExample: null,
    responseExample: {
      data: [
        {
          id: 12,
          name: 'مجموعة الخليج للإعلام',
          seatsUsed: 42,
          seatsTotal: 50,
          slaExpiry: '2026-12-01',
          whiteLabel: true,
          manager: 'أحمد خالد',
        },
      ],
      total: 1,
    },
  },
  {
    id: 'plans-list',
    group: G.dashboard,
    title: 'باقات الاشتراك (Subscription Plans)',
    method: 'GET',
    path: '/plans',
    description: 'تُستخدم في محرر الباقات وصفحة الاشتراكات.',
    auth: true,
    requestExample: null,
    responseExample: {
      data: [
        {
          id: 'pro',
          name: 'الباقة الاحترافية',
          priceMonthly: 15,
          priceYearly: 144,
          currency: 'KWD',
          features: ['نشر غير محدود', 'تحليلات متقدمة', 'دعم VIP'],
          badge: 'الأكثر مبيعاً',
        },
      ],
    },
  },
  {
    id: 'analytics-summary',
    group: G.dashboard,
    title: 'ملخص التحليلات (Analytics Summary)',
    method: 'GET',
    path: '/analytics/summary',
    description: 'بطاقات الإحصائيات في لوحة التحكم ال��ئيسية.',
    auth: true,
    requestExample: null,
    responseExample: {
      mrr: '48,200',
      churnRate: '2.1',
      activeUsers: '8,402',
      revenueSeries: [12, 18, 15, 22, 28, 25, 31],
    },
  },
  {
    id: 'payments-list',
    group: G.dashboard,
    title: 'الفواتير والمدفوعات (Payments)',
    method: 'GET',
    path: '/payments',
    description: 'جدول المعاملات المالية وصفحة المدفوعات.',
    auth: true,
    requestExample: null,
    responseExample: {
      data: [
        {
          id: 'inv_8842',
          customer: 'خالد الفهد',
          amount: 15.0,
          currency: 'KWD',
          status: 'paid',
          method: 'knet',
          createdAt: '2026-06-18T14:02:00Z',
        },
      ],
      total: 1,
    },
  },
  {
    id: 'staff-role',
    group: G.dashboard,
    title: 'تحديث صلاحية موظف (Update Role)',
    method: 'PUT',
    path: '/staff/:id/role',
    description: 'تغيير دور الموظف من مصفوفة الصلاحيات.',
    auth: true,
    requestExample: { role: 'content_manager' },
    responseExample: { success: true, id: 4, role: 'content_manager' },
  },

  // ── 14. ACCOUNT SECURITY (2FA & MAGIC LINK) ─────────────────────────────
  {
    id: 'auth-2fa-setup',
    group: G.security,
    title: 'تفعيل المصادقة الثنائية (2FA Setup)',
    method: 'POST',
    path: '/auth/2fa/setup',
    description: 'بدء تفعيل المصادقة الثنائية (TOTP). يُعيد سرّاً ورمز QR لمسحه بتطبيق Authenticator.',
    auth: true,
    requestExample: { method: 'totp' },
    responseExample: {
      secret: 'JBSWY3DPEHPK3PXP',
      otpauthUrl: 'otpauth://totp/ASKCREW:sara@example.com?secret=JBSWY3DPEHPK3PXP&issuer=ASKCREW',
      qrImage: 'data:image/png;base64,iVBORw0KGgo...',
    },
  },
  {
    id: 'auth-2fa-verify',
    group: G.security,
    title: 'التحقق من رمز 2FA (Verify 2FA)',
    method: 'POST',
    path: '/auth/2fa/verify',
    description:
      'التحقق من الرمز المكوّن من 6 أرقام لإتمام تسجيل الدخول أو تأكيد تفعيل المصادقة الثنائية. يُعيد رموز استرداد عند النجاح.',
    auth: true,
    requestExample: { code: '482913' },
    responseExample: {
      verified: true,
      twoFAEnabled: true,
      recoveryCodes: ['a1b2-c3d4', 'e5f6-g7h8', 'i9j0-k1l2'],
    },
  },
  {
    id: 'auth-magic-link-request',
    group: G.security,
    title: 'طلب رابط الدخول السحري (Magic Link)',
    method: 'POST',
    path: '/auth/magic-link/request',
    description: 'إرسال رابط دخول لمرة واحدة (Passwordless) إلى بريد المستخدم. صالح لمدة 15 دقيقة.',
    auth: false,
    requestExample: { email: 'sara@example.com', redirectTo: '/dashboard' },
    responseExample: { sent: true, expiresInSec: 900, channel: 'email' },
  },
  {
    id: 'auth-magic-link-verify',
    group: G.security,
    title: 'تأكيد رابط الدخول السحري (Verify Magic Link)',
    method: 'POST',
    path: '/auth/magic-link/verify',
    description: 'استبدال توكن الرابط السحري المؤقّت بجلسة JWT كاملة بعد نقر المستخدم للرابط.',
    auth: false,
    requestExample: { token: 'ml_9f8a7b6c5d4e3f2a1b0c' },
    responseExample: {
      token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
      user: { id: 101, name: 'سارة محمد', role: 'freelancer' },
    },
  },

  // ── 15. VOD DEVICE PAIRING ("Watch via Code") ───────────────────────────
  {
    id: 'devices-pair',
    group: G.devicePairing,
    title: 'ربط جهاز برمز (Pair Viewer Device)',
    method: 'POST',
    path: '/devices/pair',
    description:
      'ربط جهاز مشاهدة خارجي (تلفاز ذكي / كونسول) بإدخال رمز الاقتران (6-8 خانات) الظاهر على شاشة الجهاز. الباك-إند يربط الجلسة عبر WebSockets أو Polling قصير المدى.',
    auth: true,
    requestExample: { pairingCode: 'ABCD-1234' },
    responseExample: {
      success: true,
      deviceId: 'DEV-ABCD',
      message: 'Device successfully linked. Your content will start playing on your TV shortly.',
    },
  },
  {
    id: 'devices-list',
    group: G.devicePairing,
    title: 'الأجهزة المرتبطة (Paired Devices)',
    method: 'GET',
    path: '/devices',
    description: 'جلب قائمة أجهزة المشاهدة المرتبطة بالحساب مع حالة البث المباشر لكل جهاز.',
    auth: true,
    requestExample: null,
    responseExample: {
      data: [
        {
          id: 'DEV-TV-01',
          name: 'Samsung Smart TV',
          kind: 'tv',
          location: 'الصالة — الكويت',
          lastActive: '2026-06-23T19:40:00Z',
          streaming: true,
        },
      ],
      total: 1,
    },
  },
  {
    id: 'devices-unlink',
    group: G.devicePairing,
    title: 'فصل جهاز (Unlink Device)',
    method: 'DELETE',
    path: '/devices/:id',
    description:
      'إنهاء جلسة المشاهدة على جهاز مرتبط وإلغاء ربطه فوراً. يُغلق اتصال WebSocket للجهاز ويوقف أي بث جارٍ.',
    auth: true,
    requestExample: null,
    responseExample: { success: true, deviceId: 'DEV-TV-01', remainingDevices: 2 },
  },

  // ── 16. PROFILE EXPORT & MICRO-TRANSACTIONS ─────────────────────────────
  {
    id: 'profile-export-free',
    group: G.profileExport,
    title: 'تصدير مجاني بعلامة مائية (Free Watermarked Export)',
    method: 'GET',
    path: '/api/users/:id/export/free',
    description:
      'إنشاء وتنزيل ملف PDF للملف الشخصي للمستخدم مع طبع شعار ASK CREW كعلامة مائية. متاح للجميع مجاناً دون أي خصم من المحفظة. يقابل دالة الواجهة downloadProfile(userId, { watermark: true }).',
    auth: true,
    requestExample: null,
    responseExample: {
      success: true,
      fileName: 'ASKCREW_Profile_منى_الصباح_Watermarked.pdf',
      url: 'https://docs.askcrew.com/profiles/1.pdf?wm=1',
      watermarked: true,
      chargedKwd: 0,
      message: 'تم إنشاء الملف الشخصي بنجاح مع شعار ASK CREW.',
    },
  },
  {
    id: 'profile-export-premium',
    group: G.profileExport,
    title: 'تصدير مدفوع بدون شعار (Premium White-label Export)',
    method: 'POST',
    path: '/api/users/:id/export/premium',
    description:
      'معاملة دقيقة (Micro-transaction): يخصم المبلغ المحدد (amountKwd) من الرصيد المتاح في محفظة المستخدم أولاً، ثم يُنشئ ملف PDF نظيفاً بدون أي علامة مائية (White-label). إذا كان الرصيد غير كافٍ يُرجِع الخطأ 402 (Payment Required) دون توليد الملف. يجب ربط هذا المسار بنفس دفتر حسابات المحفظة المستخدم في /wallet لضمان انعكاس الخصم في كل أنحاء النظام. يقابل دالة الواجهة payAndDownloadProfile(userId, 1.00).',
    auth: true,
    requestExample: { amountKwd: 1.0, currency: 'KWD' },
    responseExample: {
      success: true,
      fileName: 'ASKCREW_Profile_منى_الصباح_Premium.pdf',
      url: 'https://docs.askcrew.com/profiles/1.pdf?wm=0',
      watermarked: false,
      chargedKwd: 1.0,
      walletBalanceKwd: 3819.0,
      message: 'تم خصم 1.00 د.ك من محفظتك وتنزيل الملف بدون شعار.',
    },
  },

  // ── 17. BOOKINGS, TRUST & BNPL ──────────────────────────────────────────
  {
    id: 'user-portfolio',
    group: G.bookingsTrust,
    title: 'معرض الأعمال (Portfolio / Showreel)',
    method: 'GET',
    path: '/api/users/:id/portfolio',
    description:
      'عناصر معرض الأعمال (فيديو وصور) المعروضة في لوحة تفاصيل المستخدم. كل عنصر يحمل النوع (video | image)، الصورة المصغّرة، ومدّة/عدد مشاهدات للفيديو.',
    auth: true,
    requestExample: null,
    responseExample: [
      { id: 'pf-set', type: 'video', title: 'كواليس إنتاج درامي', thumbnail: '/portfolio/showreel-set.png', duration: '2:14', views: 48200 },
      { id: 'pf-headshot', type: 'image', title: 'جلسة تصوير احترافية', thumbnail: '/portfolio/headshot.png' },
    ],
  },
  {
    id: 'user-availability',
    group: G.bookingsTrust,
    title: 'رزنامة التوفر (Availability Calendar)',
    method: 'GET',
    path: '/api/users/:id/availability',
    description:
      'يرجّع التواريخ المحجوزة/غير المتاحة للشهر الحالي لتعطيلها في الرزنامة، إضافة إلى السعر اليومي الافتراضي لتعبئة نموذج الحجز.',
    auth: true,
    requestExample: null,
    responseExample: {
      userId: 1,
      month: '2026-06',
      bookedDates: ['2026-06-07', '2026-06-14', '2026-06-21'],
      dayRateKwd: 450,
    },
  },
  {
    id: 'user-bookings',
    group: G.bookingsTrust,
    title: 'سجل الحجوزات (Booking History)',
    method: 'GET',
    path: '/api/users/:id/bookings',
    description: 'الحجوزات السابقة (مكتملة) والقادمة الخاصة بالمستخدم لعرضها كخطّ زمني في اللوحة.',
    auth: true,
    requestExample: null,
    responseExample: [
      { id: 'bk-101', userId: 1, title: 'مسلسل "ليالي الخليج"', date: '12 مايو 2026', status: 'completed', role: 'منتجة تنفيذية', amountKwd: 3200 },
      { id: 'bk-103', userId: 1, title: 'فيلم وثائقي', date: '20 يوليو 2026', status: 'upcoming', role: 'منتجة تنفيذية', amountKwd: 2800 },
    ],
  },
  {
    id: 'booking-create',
    group: G.bookingsTrust,
    title: 'إنشاء حجز (Create Booking)',
    method: 'POST',
    path: '/api/bookings/create',
    description:
      'ينشئ حجزاً للمستخدم المستهدف في التاريخ المحدد. عند الدفع من المحفظة (method=wallet) يُخصم المبلغ مباشرة ويُرجِع 402 إن لم يكفِ الرصيد. وعند التقسيط (method=bnpl) يُوجَّه الدفع لمزوّد BNPL (تابي/تمارا) ويُربط بالـ webhook لتأكيد التسوية.',
    auth: true,
    requestExample: {
      userId: 1,
      date: '2026-06-25',
      note: 'تصوير إعلان ليوم كامل',
      amountKwd: 450,
      payment: { method: 'bnpl', provider: 'tabby', installments: 4 },
    },
    responseExample: {
      success: true,
      bookingId: 'bk-901',
      status: 'upcoming',
      message: 'تم إنشاء الحجز وتقسيم المبلغ على 4 دفعات عبر تابي.',
    },
  },
  {
    id: 'bnpl-checkout',
    group: G.bookingsTrust,
    title: 'جلسة دفع بالتقسيط (BNPL Checkout — Tabby/Tamara)',
    method: 'POST',
    path: '/api/payments/bnpl/checkout',
    description:
      'ينشئ جلسة دفع بالتقسيط مع المزوّد المختار ويُرجِع رابط التحويل (checkoutUrl) وقيمة كل دفعة. يؤكّد الـ webhook (POST /api/payments/bnpl/webhook) التسوية لاحقاً على الخادم.',
    auth: true,
    requestExample: { provider: 'tamara', amountKwd: 450, installments: 4 },
    responseExample: {
      success: true,
      provider: 'tamara',
      checkoutUrl: 'https://checkout.tamara.com/session/172...',
      installments: 4,
      installmentKwd: 112.5,
      message: 'تم إنشاء جلسة دفع عبر تمارا — 4 دفعات بقيمة 112.50 د.ك لكل دفعة.',
    },
  },
  {
    id: 'message-send',
    group: G.bookingsTrust,
    title: 'إرسال رسالة (Send Message)',
    method: 'POST',
    path: '/api/messages/send',
    description: 'يبدأ/يكمل محادثة مع المستخدم من زر المراسلة السريع في اللوحة.',
    auth: true,
    requestExample: { userId: 1, text: 'مرحباً، نود مناقشة مشروع قادم.' },
    responseExample: { success: true, threadId: 'thread-1' },
  },
  {
    id: 'user-favorite',
    group: G.bookingsTrust,
    title: 'إضافة/إزالة من المفضلة (Toggle Shortlist)',
    method: 'POST',
    path: '/api/users/:id/favorite',
    description: 'يضيف المستخدم إلى قائمة الاختصار (Shortlist) أو يزيله منها.',
    auth: true,
    requestExample: { favorite: true },
    responseExample: { success: true, favorite: true },
  },
  {
    id: 'user-report',
    group: G.bookingsTrust,
    title: 'الإبلاغ عن مستخدم (Report Profile)',
    method: 'POST',
    path: '/api/users/:id/report',
    description: 'يرفع بلاغاً عن المستخدم لفريق الإشراف مع ذكر السبب.',
    auth: true,
    requestExample: { reason: 'سلوك غير لائق في المحادثة.' },
    responseExample: { success: true },
  },

  // ── 18. ASSETS MARKETPLACE & E-COMMERCE ─────────────────────────────────
  {
    id: 'assets-list',
    group: G.assetsMarket,
    title: 'قائمة الأصول (List Assets)',
    method: 'GET',
    path: '/api/assets',
    description:
      'يرجّع كل الأصول القابلة للتأجير/الشراء (استديوهات، مواقع، معدات، مسارح، صالات، مركبات، إكسسوارات، أزياء، مونتاج، إعاشة، تصاريح). يدعم الفلترة بالنوع عبر ?type= والبحث عبر ?q=. لكل أصل حقل metadata حر يُعرض تلقائياً.',
    auth: true,
    requestExample: null,
    responseExample: [
      {
        id: 'AST-EQP-03',
        name: 'كاميرا ARRI Alexa Mini LF',
        type: 'equipment',
        provider: 'بدر للمعدات',
        country: 'الكويت',
        city: 'حولي',
        availableIn: ['الكويت', 'السعودية', 'الإمارات'],
        transactionTypes: ['rent', 'buy'],
        dayRateKwd: 220,
        purchaseKwd: 18500,
        condition: 'used',
        isShippable: true,
        deliveryFeeKwd: 25,
        rating: 5.0,
        reviewCount: 48,
        metadata: { الدقة: '4.5K', 'عدد العدسات': 6 },
      },
    ],
  },
  {
    id: 'asset-details',
    group: G.assetsMarket,
    title: 'تفاصيل أصل (Asset Details)',
    method: 'GET',
    path: '/api/assets/:id',
    description: 'يرجّع التفاصيل الكاملة لأصل واحد، بما فيها الصور وبيانات الموقع الجغرافي والحقول الديناميكية.',
    auth: true,
    requestExample: null,
    responseExample: {
      id: 'AST-STD-01',
      name: 'استديو نون الكبير (Stage A)',
      type: 'studio',
      transactionTypes: ['rent'],
      dayRateKwd: 850,
      capacity: null,
      hasParking: true,
      metadata: { المساحة: '600 م²', 'ارتفاع السقف': '8 أمتار' },
    },
  },
  {
    id: 'asset-availability',
    group: G.assetsMarket,
    title: 'توفر الأصل (Asset Availability)',
    method: 'GET',
    path: '/api/assets/:id/availability',
    description: 'يرجّع التواريخ المحجوزة/غير المتاحة للشهر الحالي لتعطيلها في رزنامة الحجز.',
    auth: true,
    requestExample: null,
    responseExample: { assetId: 'AST-STD-01', month: '2026-06', bookedDates: ['2026-06-06', '2026-06-12', '2026-06-18'] },
  },
  {
    id: 'asset-book',
    group: G.assetsMarket,
    title: 'حجز أصل للتأجير (Book Asset / Rental)',
    method: 'POST',
    path: '/api/assets/book',
    description:
      'ينشئ حجز تأجير للأصل لعدد أيام محدد. يُخصم المبلغ من المحفظة (يُرجِع 402 إن لم يكفِ الرصيد). عند shipping=true تُجدول خدمة الشحن إلى موقع العميل.',
    auth: true,
    requestExample: { assetId: 'AST-EQP-03', date: '2026-06-25', days: 3, shipping: true, amountKwd: 685 },
    responseExample: { success: true, bookingId: 'ABK-481920', status: 'confirmed', message: 'تم تأكيد حجز الأصل وجدولة شحنه إلى موقعك.' },
  },
  {
    id: 'order-create',
    group: G.assetsMarket,
    title: 'إنشاء طلب شراء (Create Order / Buy)',
    method: 'POST',
    path: '/api/ecommerce/orders/create',
    description:
      'ينشئ طلب شراء (تملّك كامل) لأصل قابل للبيع مع بيانات عنوان التوصيل ورسوم الشحن. يُرجِع رقم الطلب وحالته الأولية.',
    auth: true,
    requestExample: {
      assetId: 'AST-EQP-03',
      transactionType: 'buy',
      quantity: 1,
      address: { fullName: 'منى الصباح', phone: '+96599000000', country: 'الكويت', city: 'السالمية', line: 'قطعة 10، شارع 5، منزل 7' },
      itemKwd: 18500,
      deliveryFeeKwd: 25,
      totalKwd: 18525,
    },
    responseExample: { success: true, orderId: 'ORD-5001', status: 'processing', totalKwd: 18525, message: 'تم إنشاء طلب الشراء ORD-5001.' },
  },
  {
    id: 'order-track',
    group: G.assetsMarket,
    title: 'تتبّع الطلب (Track Order)',
    method: 'GET',
    path: '/api/ecommerce/orders/track',
    description: 'يرجّع حالة الشحنة والخطوط الزمنية للتسليم (قيد المعالجة → تم الشحن → خرج للتوصيل → تم التسليم).',
    auth: true,
    requestExample: null,
    responseExample: {
      orderId: 'ORD-5001',
      status: 'out_for_delivery',
      carrier: 'أرامكس الكويت',
      trackingNumber: 'AWB-5001',
      etaLabel: 'خلال 24 ساعة',
      steps: [
        { status: 'processing', label: 'تم استلام الطلب', date: '20 يونيو 2026', done: true },
        { status: 'delivered', label: 'تم التسليم', date: '—', done: false },
      ],
    },
  },

  // ── 19. PRODUCTION MANAGER SUITE ────────────────────────────────────────
  {
    id: 'production-budget',
    group: G.productionSuite,
    title: 'ميزانية الإنتاج (Production Budget)',
    method: 'GET',
    path: '/api/production/budget',
    description: 'يرجّع ميزانية المشروع المعتمدة والمصروف والمتبقي مع توزيع المصروفات حسب الفئة.',
    auth: true,
    requestExample: null,
    responseExample: {
      projectName: 'مسلسل "ليالي الخليج" — الموسم 2',
      allocatedKwd: 250000,
      spentKwd: 148500,
      remainingKwd: 101500,
      breakdown: [
        { label: 'حجوزات الطاقم (ضمان)', amountKwd: 82000 },
        { label: 'تأجير المعدات والمواقع', amountKwd: 41500 },
      ],
    },
  },
  {
    id: 'callsheet-generate',
    group: G.productionSuite,
    title: 'توليد جدول نداء (Generate Call Sheet)',
    method: 'POST',
    path: '/api/production/callsheet/generate',
    description:
      'يولّد جدول نداء يومياً من الطاقم المحجوز مع تدرّج أوقات الحضور والمشاهد المخصصة لكل فرد.',
    auth: true,
    requestExample: { date: '2026-07-01', location: 'استديو نون — Stage A', generalCallTime: '07:00', crewIds: [1, 2, 3, 4] },
    responseExample: {
      id: 'CS-48210',
      date: '2026-07-01',
      location: 'استديو نون — Stage A',
      generalCallTime: '07:00',
      rows: [{ name: 'منى الصباح', role: 'مخرجة', callTime: '07:00', location: 'استديو نون — Stage A', scenes: '12, 14, 18' }],
    },
  },
  {
    id: 'script-upload',
    group: G.productionSuite,
    title: 'رفع نص مؤمّن (Upload Script — DRM & Watermark)',
    method: 'POST',
    path: '/api/production/scripts/upload',
    description:
      'يرفع نصاً ويشفّره مع علامة مائية ديناميكية باسم المستلم لمنع التسريب (DRM). يُرجِع مستند النص مع حالته.',
    auth: true,
    requestExample: { title: 'الحلقة 12 — مسوّدة نهائية', recipient: 'منى الصباح', drmEnabled: true },
    responseExample: {
      success: true,
      document: { id: 'SCR-701', title: 'الحلقة 12 — مسوّدة نهائية', uploadedAt: '22 يونيو 2026', watermarkedFor: 'منى الصباح', sizeLabel: '2.4 ميجابايت', drmEnabled: true },
      message: 'تم رفع النص وتشفيره وإضافة علامة مائية باسم: منى الصباح.',
    },
  },
  {
    id: 'catering-book',
    group: G.productionSuite,
    title: 'حجز إعاشة (Book Catering)',
    method: 'POST',
    path: '/api/services/catering/book',
    description: 'يحجز خدمة إعاشة لموقع التصوير بعدد وجبات وخيارات غذائية محددة، ويُرجِع التكلفة التقديرية.',
    auth: true,
    requestExample: { date: '2026-07-01', meals: 30, dietaryOptions: ['نباتي'], location: 'موقع التصوير' },
    responseExample: { success: true, referenceId: 'CAT-48211', estimatedKwd: 135, message: 'تم تأكيد طلب الإعاشة (30 وجبة) بتكلفة تقديرية 135 د.ك.' },
  },
  {
    id: 'permit-apply',
    group: G.productionSuite,
    title: 'تقديم طلب تصريح/تأمين (Apply Permit & Insurance)',
    method: 'POST',
    path: '/api/services/permits/apply',
    description: 'يقدّم طلب تصريح تصوير (شارع عام/درون/إغلاق موقع) مع خيار تأمين إنتاج شامل، ويُرجِع التكلفة التقديرية.',
    auth: true,
    requestExample: { permitType: 'تشغيل طائرة مسيّرة (درون)', locationType: 'خارجي', startDate: '2026-07-01', endDate: '2026-07-05', withInsurance: true },
    responseExample: { success: true, referenceId: 'PRM-48212', estimatedKwd: 650, message: 'تم تقديم طلب تصريح "تشغيل طائرة مسيّرة (درون)". التكلفة التقديرية 650 د.ك.' },
  },

  // ── 20. CRUD & ENTITY MANAGEMENT ────────────────────────────────────────
  {
    id: 'entity-create',
    group: G.crud,
    title: 'إنشاء عنصر (Create Entity)',
    method: 'POST',
    path: '/api/:entity',
    description:
      'نقطة نهاية موحّدة لإنشاء أي عنصر إداري (مستخدم، حجز، ورشة، وظيفة، عقد، أصل). :entity يحدد النوع، والحقول تأتي ديناميكياً من النموذج. تُرجع العنصر المُنشأ مع معرّفه.',
    auth: true,
    requestExample: { user: 'شركة الأفق', service: 'استشارة فنية (20 نوفمبر)', status: 'قيد الانتظار' },
    responseExample: { success: true, id: '#BK-4821', created: true },
  },
  {
    id: 'entity-update',
    group: G.crud,
    title: 'تعديل عنصر (Update Entity)',
    method: 'PUT',
    path: '/api/:entity/:id',
    description: 'يحدّث حقول عنصر قائم. تُرسَل الحقول المتغيّرة فقط، وتُرجع النسخة المحدّثة.',
    auth: true,
    requestExample: { status: 'مؤكد' },
    responseExample: { success: true, id: '#BK-4821', updated: true },
  },
  {
    id: 'entity-delete',
    group: G.crud,
    title: 'حذف عنصر (Delete Entity)',
    method: 'DELETE',
    path: '/api/:entity/:id',
    description: 'يحذف عنصراً بعد تأكيد المستخدم في الواجهة. عملية لا رجعة فيها على الخادم.',
    auth: true,
    requestExample: null,
    responseExample: { success: true, id: '#BK-4821', deleted: true },
  },
  {
    id: 'asset-create-priced',
    group: G.crud,
    title: 'إضافة أصل بتسعير ديناميكي (Create Asset w/ Commission)',
    method: 'POST',
    path: '/api/assets',
    description:
      'ينشئ أصلاً جديداً في السوق. المزوّد يحدد سعره (vendorPrice)، وتضيف المنصة عمولتها (platformFee) ليظهر السعر النهائي (finalPrice) للعميل. ينطبق النمط ذاته على الخدمات والوظائف المدفوعة.',
    auth: true,
    requestExample: {
      name: 'كاميرا RED Komodo',
      type: 'equipment',
      city: 'الكويت',
      transactionTypes: ['rent'],
      vendorPrice: 180,
      platformFeeRate: 0.1,
    },
    responseExample: {
      success: true,
      id: 'AST-EQP-77',
      pricing: { vendorPrice: 180, platformFee: 18, finalPrice: 198, ratePercent: 10 },
    },
  },

  // ── 21. LEADERBOARDS & RANKINGS ─────────────────────────────────────────
  {
    id: 'leaderboard-get',
    group: G.leaderboard,
    title: 'قائمة المتصدرين Top 10 (Leaderboard)',
    method: 'GET',
    path: '/api/leaderboard',
    description:
      'يرجّع أفضل 10 حسب الفئة عبر ?category=freelancers|assets|projects. كل عنصر يتضمن الترتيب، اتجاه الحركة (trend)، المقياس، ونتيجة نسبية (score) لشريط التقدّم.',
    auth: true,
    requestExample: null,
    responseExample: [
      { rank: 1, trend: 0, name: 'منى الصباح', subtitle: 'منتجة تنفيذية', metricLabel: '4.9 ★ • 312 مشروع', score: 100, verified: true },
      { rank: 2, trend: 2, name: 'بدر العتيبي', subtitle: 'مدير تصوير', metricLabel: '4.8 ★ • 268 مشروع', score: 94, verified: true },
    ],
  },

  // ── 22. VOD STORE & WATCH PARTIES ───────────────────────────────────────
  {
    id: 'vod-catalog',
    group: G.vodPlus,
    title: 'دليل الأعمال (VOD Catalog)',
    method: 'GET',
    path: '/api/vod/catalog',
    description: 'يرجّع كامل مكتبة الأعمال مع خيارات الوصول (مجاني/تأجير/شراء/اشتراك) وأسعار المنتِج وحالة التنزيل دون اتصال.',
    auth: true,
    requestExample: null,
    responseExample: [
      {
        id: 'VOD-001',
        title: 'الإمبراطورية الكبرى',
        genre: 'دراما تاريخية',
        year: 2026,
        producer: 'الإنتاج الذهبي',
        rating: 4.9,
        top10Rank: 1,
        accessTiers: ['rent', 'buy', 'subscription'],
        rentKwd: 2.5,
        buyKwd: 9.9,
        offlineEnabled: true,
      },
    ],
  },
  {
    id: 'vod-top10',
    group: G.vodPlus,
    title: 'الأكثر مشاهدة Top 10 (VOD Top 10)',
    method: 'GET',
    path: '/api/vod/top10',
    description: 'يرجّع أعلى 10 أعمال مشاهدةً مرتّبةً لعرضها في شريط Top 10 على غرار نتفليكس.',
    auth: true,
    requestExample: null,
    responseExample: [{ id: 'VOD-001', title: 'الإمبراطورية الكبرى', top10Rank: 1, poster: '/vod/empire.png', rating: 4.9 }],
  },
  {
    id: 'vod-checkout',
    group: G.vodPlus,
    title: 'شراء/تأجير عمل (VOD Checkout)',
    method: 'POST',
    path: '/api/vod/checkout',
    description:
      'يخصم قيمة التأجير أو الشراء من محفظة المشاهد ويصدر تصريح وصول (entitlement). التأجير ينتهي بعد 48 ساعة، الشراء دائم. يُرجِع 402 إن لم يكفِ الرصيد.',
    auth: true,
    requestExample: { titleId: 'VOD-001', tier: 'rent', amountKwd: 2.5, offline: true },
    responseExample: {
      success: true,
      entitlementId: 'ENT-481920',
      tier: 'rent',
      expiresAt: '2026-06-25T20:00:00.000Z',
      message: 'تم تأكيد التأجير — لديك 48 ساعة للمشاهدة.',
    },
  },
  {
    id: 'watch-party-create',
    group: G.vodPlus,
    title: 'إنشاء حفلة مشاهدة (Create Watch Party)',
    method: 'POST',
    path: '/api/vod/watch-party/create',
    description:
      'ينشئ جلسة مشاهدة جماعية متزامنة لعمل محدد، يدعو المشاهدين، ويُرجِع رابط الانضمام ورمز المضيف. يدعم تفعيل الدردشة أثناء العرض.',
    auth: true,
    requestExample: { titleId: 'VOD-001', scheduledAt: '2026-06-25T21:00:00.000Z', invitees: ['نورة', 'أحمد', 'سارة'], chatEnabled: true },
    responseExample: {
      success: true,
      partyId: 'WP-481920',
      joinUrl: 'https://watch.askcrew.tv/party/WP-481920',
      hostToken: 'host-WP-481920',
      message: 'تم إنشاء حفلة مشاهدة ودعوة 3 مشاهد.',
    },
  },
]

/** Ordered list of groups as they should appear in the UI / Postman folders. */
export const API_GROUPS: string[] = Object.values(G)
