import {
  LayoutDashboard,
  Building2,
  Users,
  CreditCard,
  BarChart3,
  ShieldCheck,
  Settings,
  Images,
  Lock,
  MessageSquare,
  GraduationCap,
  LayoutTemplate,
  Award,
  Plug,
  CalendarCheck,
  Receipt,
  Wallet,
  Scale,
  Globe2,
  BadgeCheck,
  LifeBuoy,
  BellRing,
  Terminal,
  Clock,
  Code2,
  FileJson,
  FileSignature,
  Film,
  Wrench,
  MonitorSmartphone,
  Boxes,
  ClipboardList,
  type LucideIcon,
} from 'lucide-react'

export type NavItem = {
  /** i18n key under the `nav` namespace (see lib/i18n/messages). */
  key: string
  /** Arabic fallback label (used if i18n hasn't loaded). */
  label: string
  href: string
  icon: LucideIcon
}

export const navItems: NavItem[] = [
  { key: 'home', label: 'الرئيسية', href: '/dashboard', icon: LayoutDashboard },
  { key: 'users', label: 'المستخدمين', href: '/dashboard/users', icon: Users },
  { key: 'plans', label: 'الاشتراكات', href: '/dashboard/packages', icon: CreditCard },
  { key: 'posters', label: 'إدارة البوسترات', href: '/dashboard/posters', icon: Images },
  { key: 'content', label: 'إدارة المحتوى', href: '/dashboard/content', icon: LayoutTemplate },
  { key: 'community', label: 'الدردشة والمجتمع', href: '/dashboard/chat', icon: MessageSquare },
  { key: 'workshops', label: 'ورش العمل والوظائف', href: '/dashboard/workshops', icon: GraduationCap },
  { key: 'assets', label: 'المعدات والمواقع', href: '/dashboard/assets', icon: Boxes },
  { key: 'bookings', label: 'الحجوزات', href: '/dashboard/bookings', icon: CalendarCheck },
  { key: 'payments', label: 'المدفوعات', href: '/dashboard/payments', icon: Receipt },
  { key: 'earnings', label: 'المحفظة والضمان', href: '/dashboard/wallet', icon: Wallet },
  { key: 'rewards', label: 'الجوائز والخصومات', href: '/dashboard/rewards', icon: Award },
  { key: 'tickets', label: 'التذاكر والدعم', href: '/dashboard/tickets', icon: LifeBuoy },
  { key: 'notifications', label: 'الإشعارات', href: '/dashboard/notifications', icon: BellRing },
  { key: 'siteSettings', label: 'إعدادات الموقع', href: '/dashboard/site-settings', icon: Globe2 },
 // { key: 'analytics', label: 'التحليلات', href: '/dashboard/analytics', icon: BarChart3 },
   //{ key: 'disputes', label: 'فض النزاعات', href: '/dashboard/disputes', icon: Scale },
    // { key: 'vod', label: 'الفيديو و DRM', href: '/dashboard/vod', icon: Film },
  // { key: 'production', label: 'غرفة عمليات الإنتاج', href: '/dashboard/production', icon: ClipboardList },
  // { key: 'companies', label: 'الشركات', href: '/dashboard/companies', icon: Building2 },
  // { key: 'contracts', label: 'العقود والتوقيعات', href: '/dashboard/contracts', icon: FileSignature },
  //  { key: 'devicePairing', label: 'ربط أجهزة المشاهدة', href: '/dashboard/device-pairing', icon: MonitorSmartphone },
  //  { key: 'kyc', label: 'التحقق من الهويات', href: '/dashboard/kyc', icon: BadgeCheck },
  // { key: 'access', label: 'الصلاحيات', href: '/dashboard/access', icon: ShieldCheck },
  // { key: 'security', label: 'حماية المحتوى', href: '/dashboard/security', icon: Lock },
  // { key: 'integrations', label: 'التحقق والربط', href: '/dashboard/integrations', icon: Plug },
  // { key: 'logs', label: 'سجل النظام', href: '/dashboard/logs', icon: Terminal },
  // { key: 'cron', label: 'المهام والنسخ', href: '/dashboard/cron', icon: Clock },
  // { key: 'developer', label: 'إعدادات المطورين', href: '/dashboard/developer', icon: Code2 },
  // { key: 'apiSpecs', label: 'مواصفات الربط', href: '/dashboard/api-specs', icon: FileJson },
  // { key: 'devTools', label: 'أدوات المطورين', href: '/dashboard/dev-tools', icon: Wrench },
 // { key: 'settings', label: 'الإعدادات', href: '/dashboard/settings', icon: Settings },
]
